const fs = require('fs');
const path = require('path');
const OUTPUT = path.join(__dirname, '..', 'data', 'questions', 'basics.js');

function q(id, question, opts, correct, topic, subSkill, cog, diff, err, exp, a, b, c, subs, diag, pre, quick) {
  return { id, question, options: opts, correct, topic, subSkill, cognitiveLevel: cog, difficulty: diff, errorPattern: err, explanation: exp, irt: { a: a, b: b, c: c }, subSkills: subs, diagnostic: diag, prerequisites: pre, isQuick: quick };
}

const QUESTIONS = [

// ============================================================
// general-concepts: 30 comprehensive + 12 quick
// ============================================================
q('gc_001','ما هو تعريف الشبكة الحاسوبية؟',['جمع حواسيب ومشاركة الموارد','.شبكة محصورة في جهاز واحد','مجرد برنامج تطبيقي ويب','هارديسك خارجي'],0,'general-concepts','network_def','remembering',1,'memorization','الشبكة الحاسوبية هي مجموعة من الأجهزة المتصلة ببعضها البعض لمشاركة الموارد والاتصال.',0.9,-2.0,0.2,['network_def'],{errorPattern:'misc_def_network',rootCause:'يبسّط مفهوم الشبكة إلى مجرد اتصال أو برنامج',futureImpact:'صعوبة في فهم بنية الشبكات المعقدة',remediationVideoQuery:'ما هي الشبكة الحاسوية وما هي أهدافها'},[],false),
q('gc_002','ما الفرق بين LAN و WAN؟',['تغطي الـ LAN منطقة جغرافية صغيرة محدودة، تغطي الـ WAN مسافات كبيرة','.تطلب الـ LAN إنترنت بطيء وتتطلب الـ WAN إنترنت سريع','تستخدم الـ LAN منافذ لاسلكية فقط بينما الـ WAN سلكية فقط','لا يوجد فرق حقيقي'],0,'general-concepts','network_types','understanding',1,'conceptual','الـ LAN تغطي موقع جغرافي صغير مثل المبنى، أما WAN تغطي مسافات كبيرة مثل المدن.',0.9,-1.5,0.2,['network_def','network_types'],{errorPattern:'misc_lan_wan',rootCause:'يخلط بين نوعية الاتصال والنطاق الجغرافي',futureImpact:'اختيار نوع شبكة غير مناسب للمتطلبات',remediationVideoQuery:'الفرق بين LAN و WAN'},[],false),
q('gc_003','أي من التالي ليس من نوع بروتوكول؟',['HTTP','TCP','IP','CPU'],3,'general-concepts','protocols','remembering',1,'memorization','البروتوكول هو مجموعة قواعد للاتصال. CPU هو المعالج وليس بروتوكولاً.',1.0,-2.5,0.2,['protocols'],{errorPattern:'misc_protocol_device',rootCause:'يمزيج بين الأجهزة والبروتوكولات',futureImpact:'عدم القدرة على تطبيق بروتوكولات التواصل',remediationVideoQuery:'ما هو البروتوكول في الشبكات؟'},[],false),
q('gc_004','ما هي طبولوجيا الشبكة النجمية؟',['كل أجهزة متصلة في خط مستقيم','جميع الأجهزة مركزية حول مفتاح مركزي','كل جهاز متصل بالجهاز الذي له جانبه','الأجهزة متصلة في حلقة مغلقة'],1,'general-concepts','network_topologies','remembering',1,'memorization','في الطبولوجيا النجمية يتصل كل جهاز بجهاز مركزي مثل سويتش.',0.8,-1.8,0.2,['network_def'],{errorPattern:'misc_topology',rootCause:'عدم تمييز الطبولوجيا عن نوع الاتصال',futureImpact:'تصميم شبكات غير صالحة',remediationVideoQuery:'أنواع طبولوجيا الشبكات'},[],false),
q('gc_005','ما هو الـ Bandwidth؟',['عدد الأجهزة المتصلة','سرعة نقل البيانات القصوى','عدد البروتوكولات المدعومة','مقدار الذاكرة المخصصة للشبكة'],1,'general-concepts','bandwidth','remembering',2,'conceptual','الـ Bandwidth هو السعة القصوى لنقل البيانات عبر الرابط تُقاس بالبت/ثانية.',0.9,-1.2,0.2,['net_fund','network_perf'],{errorPattern:'misc_bandwidth_def',rootCause:'عدم فهم مفهوم السعة مقابل السرعة',futureImpact:'اختيار روابط غير كافية',remediationVideoQuery:'ما هو الـ Bandwidth؟'},[],false),
q('gc_006','ما الفرق بين Latency والـ Bandwidth؟',['الـ Bandwidth يقاس بالبت/ثانية بينما الـ Latency تُقاس بالثواني','الـ Latency أكبر من الـ Bandwidth دائماً','هما نفس الشيء','الـ Bandwidth يقلل دائماً الـ Latency'],0,'general-concepts','bandwidth','understanding',2,'conceptual','الـ Bandwidth هو السعة القصوى للنقل، أما Latency فهو زمن الوصول. قد تكون لديك سعة عالية لكن زمنًا بطيئًا.',0.9,-0.8,0.2,['network_perf'],{errorPattern:'misc_bandwidth_latency',rootCause:'إخلاط السعة بالوقت',futureImpact:'تحديد شبكات غير مناسبة',remediationVideoQuery:'الفرق بين Latency و Bandwidth'},[],false),
q('gc_007','ما خاصية بروتوكول DHCP؟',['يحوّل أسماء النطاقات إلى عناوين IP','يوفر عناوين IP وإعدادات شبكة للأجهزة تلقائياً','يشفر البيانات أثناء النقل','يدمن أمان الشبكة'],1,'general-concepts','protocols','understanding',2,'conceptual','بروتوكول DHCP يخصص عناوين IP وإعدادات الشبكة للأجهزة تلقائياً.',0.8,-1.0,0.2,['dhcp'],{errorPattern:'misc_dhcp_dns',rootCause:'يخلط بين خدمات IP والـ DNS',futureImpact:'مشاكل في توزيع العناوين',remediationVideoQuery:'كيف يعمل بروتوكول DHCP؟'},[],false),
q('gc_008','ما هو الـ DNS؟',['يدير قواعد بيانات على الخوادم','يترجم أسماء النطاقات إلى عناوين IP','يدير الوقت والتاريخ','يقسم الشبكة إلى شبكات فرعية'],1,'general-concepts','naming','remembering',1,'memorization','الـ DNS يترجم أسماء مواقع مثل google.com إلى عناوين IP.',0.9,-2.2,0.2,['dns'],{errorPattern:'misc_dns_role',rootCause:'يظن أن الـ DNS يخزن البيانات',futureImpact:'فشل في الوصول للمواقع',remediationVideoQuery:'ما هو الـ DNS ولماذا نحتاجه؟'},[],false),
q('gc_009','ما هي الحوسبة السحابية؟',['كويكب في السماء','خدمة إنترنتية توفر موارد حوسبة عبر الإنترنت','برنامج لتشغيل الخووادس المحلية','جهاز للنسخ الاحتياطي'],1,'general-concepts','cloud','understanding',2,'conceptual','الحوسبة السحابية توفر موارد مثل الخووادس، التخزين، والبرمجيات عبر الإنترنت بدون بنية تحتية محلية.',0.8,-0.5,0.2,['net_fund','cloud'],{errorPattern:'misc_cloud',rootCause:'لامعي رفهية الحوسبة السحابية',futureImpact:'اختيار حلول تكنولوجية غير مناسبة',remediationVideoQuery:'شرح الحوسبة السحابية ببساطة'},[],false),
q('gc_010','ما هو الـ MAC Address؟',['عنوان منطقي يمنحه الإنسان','عنوان فريد ثابت لكرت الشبكة على الطبقة الثانية','رقم هوية المستخدم','عنوان IP ديناميكي'],1,'general-concepts','mac_addressing','remembering',1,'memorization','الـ MAC Address هو عنوان فريد ثابت لكرت الشبكة مكوّن من 6 بايت (48 بت).',0.8,-1.5,0.2,['mac_addressing'],{errorPattern:'misc_mac_def',rootCause:'إخلاط العنوان المادي بالمنطقي',futureImpact:'أخطاء في التوجيه والعنونة',remediationVideoQuery:'ما هو الـ MAC Address؟'},[],false),
q('gc_011','ما الفرق بين Half-Duplex و Full-Duplex؟',['الـ Half إرسال واستقبال في آن واحد، الـ Full على قنوات منفصلة','الـ Full أبطأ','الـ Half لا يدعم الاتصال المزدوج','هما نفس الشيء'],0,'general-concepts','wireless','understanding',2,'conceptual','الـ Half-Duplex يتواصل طرفا الاتصال بشكل متبادلي، أما Full-Duplex فيتيح لهما الإرسال والاستقبال في آن واحد.',0.9,-0.3,0.2,['ethernet'],{errorPattern:'misc_duplex',rootCause:'إخلاط الاتصال المزدوج بالسرعة',futureImpact:'مشاكل اتصال وتصادم بيانات',remediationVideoQuery:'Half-Duplex مقابل Full-Duplex'},[],false),
q('gc_012','ما هو الـ Packet؟',['ملف تنفيذ برنامج','وحدة بيانات تُرسل عبر الشبكة','نوع من استثمار التكنولوجيا','طريقة لضغط البيانات'],1,'general-concepts','transmission','remembering',1,'memorization','الـ Packet هو وحدة البيانات الأساسية التي تُرسل عبر الشبكة، تحتوي على بيانات ومعلومات تحكم.',0.8,-1.8,0.2,['net_fund'],{errorPattern:'misc_packet',rootCause:'عدم فهم وحدة نقل البيانات الأساسية',futureImpact:'صعوبة في تحليل حركة البيانات',remediationVideoQuery:'ما هو الحزمة Packet؟'},[],false),
q('gc_013','ماذا يحدث عند Encapsulation؟',['تشفير البيانات بالكامل','إضافة رؤوس بروتوكولات الطبقة للحزمة','حذف البيانات غير الضرورية','تحويل البيانات من لاسلكية إلى سلكية'],1,'general-concepts','transmission','understanding',2,'conceptual','عند التغليف، تضيف كل طبقة بياناتها الخاصة إلى الحزمة من الأسفل إلى الأعلى.',0.9,-0.5,0.2,['net_fund'],{errorPattern:'misc_encapsulation',rootCause:'عدم فهم آلية التغليف بين الطبقات',futureImpact:'عدم القدرة على تتبع البيانات',remediationVideoQuery:'كيف يعمل التغليف؟'},[],false),
q('gc_014','ما الفرق بين Unicast متعدد المتكررات و Broadcast؟',['الـ Unicast لجهاز واحد، الـ Multicast لمجموعة، الـ Broadcast للجميع','الـ Broadcast أسرع من الـ Unicast','الـ Multicast غير مستخدم في الشبكات الحديثة','مصطلحات مترادفة'],0,'general-concepts','transmission','understanding',3,'conceptual','الـ Unicast نقل نقطة-نقطة، Multicast نقل نقطة-متعدد، Broadcast إلى جميع الأجهزة.',0.9,-0.2,0.2,['net_fund'],{errorPattern:'misc_multicast_bcast',rootCause:'عدم التمييز بين أنماط النقل',futureImpact:'استخدام نمط نقل غير فعال',remediationVideoQuery:'أنواع نقل البيانات'},[],false),
q('gc_015','ما هي الـ QoS؟',['بروتوكول لضمان جودة الاتصال','ميكانيزم لإدارة حركة المرور وضمان أداء التطبيقات','برنامج مضاد فيروسات','طريقة لتسريع الإنترنت'],1,'general-concepts','qos','understanding',2,'conceptual','الـ QoS تمنح أولوية لحركة المرور الحيوية مثل المكالمات الصوتية عند امتلاء الرابط.',0.9,0.3,0.2,['net_fund','network_perf'],{errorPattern:'misc_qos',rootCause:'يظن أن QoS يزيد السرعة العامة',futureImpact:'تدهور جودة التطبيقات الحية',remediationVideoQuery:'ما هي الـ QoS ومتى نستخدمها؟'},[],false),
q('gc_016','ما الفرق بين OSI و TCP/IP؟',['الـ OSI له 7 طبقات، الـ TCP/IP له 4 طبقات','الـ TCP/IP أبطأ من الـ OSI','الـ OSI للإنترنت فقط','الـ TCP/IP لا يدعم التوجيه'],0,'general-concepts','network_basic','understanding',2,'conceptual','الـ OSI نموذج نظري 7 طبقات، TCP/IP نموذج عملي 4 طبقات يستخدم في الإنترنت.',0.9,-0.8,0.2,['osi_model','tcpip_model'],{errorPattern:'misc_osi_tcpip',rootCause:'عدم معرفة الفرق بين النموذجين',futureImpact:'الارتباك عند قراءة الوثائق',remediationVideoQuery:'مقارنة OSI و TCP/IP'},[],false),
q('gc_017','ما هو الـ Router؟',['جهاز يربط شبكتين ويوجه الحزم بينهما','جهاز يخزن الملفات','برنامج للبحث في الإنترنت','جهاز لتوصيل الأسلاك'],0,'general-concepts','network_basic','remembering',1,'memorization','الـ Router هو جهاز يربط شبكات مختلفة ويوجه الحزم بناءً على عناوين IP.',1.0,-2.0,0.2,['routing_fund'],{errorPattern:'misc_router_switch',rootCause:'عدم تمييز الموجه عن المفتاح',futureImpact:'اختيار جهاز خطأ للمهمة',remediationVideoQuery:'ما هو الـ Router وما هي وظيفته؟'},[],false),
q('gc_018','ما هو الـ Switch؟',['جهاز يوجه الحزم بين شبكات مختلفة','جهاز يربط الأجهزة في شبكة محلية ويتواصل بينها بعنوان MAC','برنامج مضاد للفيروسات','جهاز لتخزين البيانات'],1,'general-concepts','network_basic','remembering',1,'memorization','الـ Switch هو جهاز طبقة الرابط يربط الأجهزة داخل الشبكة المحلية ويتواصل بينها بعناوين MAC.',0.9,-1.8,0.2,['switching'],{errorPattern:'misc_router_switch',rootCause:'إخلاط وظيفة الموجه والمفتاح',futureImpact:'بناء بنية شبكة غير صحيحة',remediationVideoQuery:'الفرق بين الـ Switch والـ Router'},[],false),
q('gc_019','ما الفرق بين Static IP و Dynamic IP؟',['الـ Static يُحدد يدوياً والـ Dynamic يُعطى تلقائياً','الـ Static أبطأ','الـ Dynamic غير آمن','الـ Static لا يستخدم على الإنترنت'],0,'general-concepts','ipv4_structure','understanding',1,'conceptual','الـ Static IP ثابت ويدوي، الـ Dynamic IP يُعيّن تلقائياً من قبل DHCP ويتغير.',0.8,-1.5,0.2,['ipv4_fund'],{errorPattern:'misc_static_dynamic',rootCause:'عدم فهم طريقتي تعيين العناوين',futureImpact:'مشاكل في الاتصال وإعادة التوجيه',remediationVideoQuery:'الفرق بين Static و Dynamic IP'},[],false),
q('gc_020','ما هو الـ Hub؟',['جهاز يوزع البيانات على شبكة محلية باستخدام MAC','جهاز بسيط يتلقى الإشارة وينقلها لجميع المنافذ','جهاز يوجه الحزم بين شبكات مختلفة','جهاز لتشفير البيانات'],1,'general-concepts','network_devices','remembering',1,'memorization','الـ Hub هو جهاز بسيط يستقبل الإشارة ويبثها على جميع المنافذ، يعمل على الطبقة المادية.',1.0,-1.8,0.2,['ethernet'],{errorPattern:'misc_hub_switch',rootCause:'عدم فرق الـ Hub عن الـ Switch',futureImpact:'اختيار أدوات شبكة غير مناسبة',remediationVideoQuery:'ما هو الـ Hub وكيف يعمل؟'},[],false),
q('gc_021','ما هو الـ Firewall؟',['جهاز أو برنامج لحماية الشبكة من الوصول غير المصرح به','برنامج لتسريع الإنترنت','جهاز لتخزين النسخ الاحتياطية','طريقة لتقسيم الشبكة'],0,'general-concepts','security','understanding',2,'conceptual','الـ Firewall هو جدار حماية يراقب ويقرر منع أو السماح بحركة المرور بناءً على قواعد محددة.',0.9,-0.5,0.2,['net_fund','security'],{errorPattern:'misc_firewall',rootCause:'يفتقر إلى فهم مفهوم الأمن الشبكي',futureImpact:'تهديدات أمنية غير محسوبة',remediationVideoQuery:'ما هو الـ Firewall وماذا يحمي؟'},[],false),
q('gc_022','ما هو الـ Modem؟',['يحوّل الإشارة الرقمية إلى تناجيرية وعكسه للاتصال عبر الخطوط الهاتفية','جهاز يربط الأجهزة في شبكة محلية','برنامج لتشفير البيانات','جهاز لتقسيم الشبكة'],0,'general-concepts','network_devices','remembering',1,'memorization','الـ Modem يحوّل الإشارة الرقمية إلى تمثيلية للاتصال عبر الخطوط الهوائية أو الهاتفية.',0.8,-1.2,0.2,['ethernet'],{errorPattern:'misc_modem_router',rootCause:'يخلط بين وظيفة المودم والراوتر',futureImpact:'إعداد جهاز غير صحيح للاتصال',remediationVideoQuery:'ما هو الـ Modem وكيف يعمل؟'},[],false),
q('gc_023','ما الفرق بين Throughput و Bandwidth؟',['الـ Throughput سرعة النقل الفعلية بينما الـ Bandwidth هي السعة القصوى المحتملة','الـ Throughput دائماً أكبر من الـ Bandwidth','هما مصطلحان مترادفان','الـ Throughput يقلل من الـ Bandwidth'],0,'general-concepts','bandwidth','understanding',2,'conceptual','الـ Bandwidth هي السعة القصوى للرابط، الـ Throughput هو المعدل الفعلي لنقل البيانات الذي قد يكون أقل باسباع الخسائر.',0.9,-0.3,0.2,['network_perf'],{errorPattern:'misc_throughput_bandwidth',rootCause:'إخلاط السعة النظرية بالسرعة الفعلية',futureImpact:'تقدير خاطئ لأداء الشبكة',remediationVideoQuery:'الفرق بين Throughput و Bandwidth'},[],false),
q('gc_024','ما هو الـ IP Address؟',['رقم هوية للمستخدم','عنوان منطقي يُعرّف كل جهاز على الشبكة','رمز للبروتوكولات','كلمة مرور الشبكة'],1,'general-concepts','ipv4_structure','remembering',1,'memorization','الـ IP Address هو عنوان منطقي يُعرّف كل جهاز على الشبكة ويستخدم للتوجيه.',0.8,-2.0,0.2,['ipv4_fund','ip_addressing'],{errorPattern:'misc_ip_def',rootCause:'عدم فهم مفهوم العنوان المنطقي',futureImpact:'مشاكل في التوجيه والاتصال',remediationVideoQuery:'ما هو الـ IP Address؟'},[],false),
q('gc_025','ما الفرق بين OSI و Internet Model؟', ['الـ OSI له 7 طبقات','الـ Internet Model بروتوكول واحد','الـ OSI غير متوفر','الـ OSI يدعم فقط الشبكات المحلية'], 0,'general-concepts','network_basic','remembering',1,'memorization','الـ OSI (Open Systems Interconnection) نموذج مرجعي يحتوي على سبع طبقات.','0.8,-1.5,0.2','0.8,-1.5,0.2',['osi_model'],{errorPattern:'misc_osi_layers',rootCause:'عدم حفظ عدد طبقات النموذج',futureImpact:'صعوبة في تحليل المشكلات',remediationVideoQuery:'طبقات نموذج OSI'},[],false)